server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST:prod-db-server}:3306/marketplace_db_prod?createDatabaseIfNotExist=true
    username: ${PROD_DB_USER:prod_user}
    password: ${PROD_DB_PASSWORD:prod_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: never
