server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://${DEV_DB_HOST:localhost}:3306/marketplace_db_dev?createDatabaseIfNotExist=true
    username: ${DEV_DB_USER:root}
    password: ${DEV_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
