server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9000
          predicates:
            - Path=/api/auth/**
        - id: auth-actuator
          uri: http://auth-service:9000
          predicates:
            - Path=/auth/actuator/**
          filters:
            - StripPrefix=1

        - id: marketplace-service
          uri: http://marketplace-service:8081
          predicates:
            - Path=/api/test/**
        - id: marketplace-actuator
          uri: http://marketplace-service:8081
          predicates:
            - Path=/marketplace/actuator/**
          filters:
            - StripPrefix=1

        - id: payment-service
          uri: http://payment-service:8082
          predicates:
            - Path=/api/payment/**
        - id: payment-actuator
          uri: http://payment-service:8082
          predicates:
            - Path=/payment/actuator/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
