spring:
  application:
    name: gateway-service

auth:
  service:
    uri: http://auth-service:9000

marketplace:
  service:
    uri: http://marketplace-service:8081

payment:
  service:
    uri: http://payment-service:8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG